/**
 * Read-only Markdown projection + one-shot curated import
 * (WorkBuddy MEMORY.md, Claude Code CLAUDE.md, Codex AGENTS.md).
 * The Markdown file is not a write-back format.
 */
import { existsSync, readFileSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { BUSINESS_EDGES, clip, looksSecret, nowIso } from "./schema.js";
import { sanitizeForWrite } from "./hygiene.js";
import {
  CHITCHAT_CUES,
  DECISION_CUES,
  MAX_LINE_CHARS,
  MAX_WRITE_CHARS,
  MAX_WRITE_ITEMS,
  ONESHOT_CUES,
  PREFERENCE_CUES,
  applyCandidates,
  firstEntityName,
} from "./extract.js";
import { parseUntilFromText } from "./until.js";
import { listOutgoingBusiness } from "./store.js";

export const EXPORT_MARKER = "dsh-trivium-export";

const WRITE_TYPES = ["preference", "decision", "entity", "experience"];

const HEADING_STOP = new Set([
  "memory",
  "memories",
  "notes",
  "note",
  "user",
  "soul",
  "identity",
  "about",
  "overview",
  "todo",
  "log",
  "logs",
  "rules",
  "记忆",
  "笔记",
  "用户",
  "关于",
  "日志",
]);

/** Imperative / contract language — used only for curated-file import, not live extract. */
const RULE_CUES =
  /必须|务必|禁止|永远不要|始终|prefer|\balways\b|\bnever\b|\bmust\b|\bdo not\b|\bdon't\b|mandatory|用.{1,24}不用|\buse\b.{1,24}\bnot\b/i;

const DATE_HEADING = /^\d{4}-\d{2}-\d{2}\b/;
const KV_LINE =
  /^(`[^`]{2,64}`|[A-Z][A-Za-z0-9._-]{1,63}|[a-z][a-z0-9]+(?:-[a-z0-9]+)+)\s*[:：]\s+(\S[\s\S]*)$/;

export function isOurMarkdownExport(text) {
  return String(text || "").slice(0, 800).includes(EXPORT_MARKER);
}

function targetName(db, edge) {
  const payload = db.get(edge.to)?.payload || {};
  if (payload.type === "entity") return String(payload.name || payload.text || "").trim();
  return String(payload.name || payload.text || edge.l0 || "").replace(/\s+/g, " ").trim();
}

function lineOf(db, payload, edges) {
  const type = payload.type;
  let body = String(payload.text || payload.name || "").replace(/\s+/g, " ").trim();
  if (type === "entity") body = String(payload.name || payload.text || "").trim();
  if (type === "decision" && payload.until && !/\buntil\b|周五|下周/i.test(body)) {
    body = `${body} until ${payload.until}`;
  }
  body = clip(body, MAX_LINE_CHARS);
  const bits = [];
  for (const e of edges || []) {
    if (!BUSINESS_EDGES.includes(e.label)) continue;
    const short = clip(targetName(db, e), 48);
    if (!short) continue;
    bits.push(`—${e.label}→ ${short}`);
  }
  const suffix = bits.length ? ` ${bits.join(" ")}` : "";
  return `- ${body}${suffix}`;
}

export function exportMarkdown(db, { cwd = "" } = {}) {
  const buckets = {
    preference: [],
    decision: [],
    entity: [],
    experience: [],
  };
  for (const id of db.allNodeIds?.() || []) {
    const node = db.get(id);
    if (!node) continue;
    const payload = node.payload || {};
    if (!WRITE_TYPES.includes(payload.type)) continue;
    if (payload.status === "archived") continue;
    const edges = listOutgoingBusiness(db, id);
    const line = lineOf(db, payload, edges);
    const extra = [];
    if (payload.type === "entity" && Array.isArray(payload.aliases) && payload.aliases.length) {
      extra.push(`  aliases: ${payload.aliases.slice(0, 8).join(", ")}`);
    }
    if (payload.type === "experience") {
      if (payload.fail) extra.push(`  fail: ${clip(payload.fail, 160)}`);
      if (payload.fix) extra.push(`  fix: ${clip(payload.fix, 160)}`);
    }
    if (payload.type === "decision" && payload.untilAt) {
      extra.push(`  untilAt: ${payload.untilAt}`);
    }
    buckets[payload.type].push({ updatedAt: payload.updatedAt || "", line, extra });
  }
  for (const type of WRITE_TYPES) {
    buckets[type].sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt)));
  }

  const lines = [
    `<!-- ${EXPORT_MARKER} v1 -->`,
    "# dsh-trivium MEMORY.md",
    "",
    "Read-only projection of the graph. Do not edit this file to write back — use Settings or JSON import.",
    `Generated ${nowIso()}${cwd ? ` from \`${cwd}\`` : ""}.`,
    `Each line clipped to ${MAX_LINE_CHARS} chars (WorkBuddy-style write discipline).`,
    "",
  ];
  for (const type of WRITE_TYPES) {
    const rows = buckets[type];
    if (!rows.length) continue;
    lines.push(`## ${type}`, "");
    for (const row of rows) {
      lines.push(row.line);
      lines.push(...row.extra);
    }
    lines.push("");
  }
  if (lines[lines.length - 1] === "") lines.pop();
  return `${lines.join("\n")}\n`;
}

function headingEntity(title) {
  const t = String(title || "")
    .replace(/^#+\s*/, "")
    .trim();
  if (!t || DATE_HEADING.test(t)) return { skipSection: DATE_HEADING.test(t), name: undefined };
  const key = t.toLowerCase().replace(/[:：].*$/, "").trim();
  if (HEADING_STOP.has(key)) return { skipSection: false, name: undefined };
  const name = firstEntityName(t);
  if (!name) return { skipSection: false, name: undefined };
  if (t.length > 64) return { skipSection: false, name: undefined };
  return { skipSection: false, name };
}

function kvParts(text) {
  const m = String(text || "").match(KV_LINE);
  if (!m) return null;
  const name = String(m[1]).replace(/`/g, "").trim();
  const rest = String(m[2] || "").trim();
  if (!name || !rest) return null;
  if (HEADING_STOP.has(name.toLowerCase())) return null;
  const ident =
    firstEntityName(name) === name ||
    /^[A-Z][A-Za-z0-9]*[A-Z][A-Za-z0-9._-]*$/.test(name) ||
    /^[A-Z]{2,12}$/.test(name) ||
    /^[a-z][a-z0-9]+(?:-[a-z0-9]+)+$/.test(name);
  if (!ident) return null;
  return { name, rest };
}

function classifyBullet(text, sectionEntity) {
  const body = String(text || "").replace(/\s+/g, " ").trim();
  if (!body) return { skip: "empty" };
  if (body.length < 8) return { skip: "too-short" };
  if (body.length > 800) return { skip: "too-long" };
  if (looksSecret(body)) return { skip: "secret" };
  if (!sanitizeForWrite(body).ok) return { skip: "dirty" };
  if (CHITCHAT_CUES.test(body)) return { skip: "chitchat" };
  if (ONESHOT_CUES.test(body)) return { skip: "oneshot" };
  if (/^\d{1,2}:\d{2}\b/.test(body) || /^#{1,6}\s/.test(body)) return { skip: "log-line" };

  const kv = kvParts(body);
  const name = kv?.name || firstEntityName(body) || sectionEntity;
  const fact = kv ? `${kv.name}: ${clip(kv.rest, MAX_LINE_CHARS - kv.name.length - 2)}` : clip(body, MAX_LINE_CHARS);

  if (DECISION_CUES.test(body)) {
    return {
      skip: null,
      candidates: [
        kv ? { type: "entity", name: kv.name, text: kv.name, via: "workbuddy-import" } : null,
        {
          type: "decision",
          name,
          text: fact,
          until: parseUntilFromText(body),
          linkName: name,
          linkLabel: "decided",
          quote: clip(body, 120),
          via: "external-import",
        },
      ].filter(Boolean),
    };
  }

  const ruleLike = PREFERENCE_CUES.test(body) || RULE_CUES.test(body) || Boolean(kv);
  if (ruleLike) {
    const out = [];
    if (kv) out.push({ type: "entity", name: kv.name, text: kv.name, via: "workbuddy-import" });
    else if (sectionEntity && name === sectionEntity) {
      out.push({ type: "entity", name: sectionEntity, text: sectionEntity, via: "workbuddy-import" });
    }
    out.push({
      type: "preference",
      name,
      text: fact,
      linkName: name,
      linkLabel: "about",
      quote: clip(body, 120),
      via: "workbuddy-import",
    });
    return { skip: null, candidates: out };
  }

  return { skip: "no-cue" };
}

export function parseWorkbuddyMarkdown(text, { sourcePath = "" } = {}) {
  const raw = String(text || "");
  if (!raw.trim()) {
    return { ok: false, message: "空文件", candidates: [], skipped: 0, sourcePath };
  }
  if (isOurMarkdownExport(raw)) {
    return {
      ok: false,
      message: "这是本插件导出的 MEMORY.md，不能当 WorkBuddy 文件回写。请用 JSON 导入或 Settings。",
      candidates: [],
      skipped: 0,
      sourcePath,
    };
  }

  const candidates = [];
  let skipped = 0;
  let sectionEntity;
  let skipSection = false;
  let inFence = false;

  for (const rawLine of raw.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (/^```/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    if (!line) continue;
    if (/^#{1,6}\s+/.test(line)) {
      const heading = headingEntity(line);
      skipSection = heading.skipSection;
      sectionEntity = heading.skipSection ? undefined : heading.name;
      continue;
    }
    if (skipSection) {
      skipped += 1;
      continue;
    }
    const bullet = line.match(/^[-*+]\s+(?:\[[ xX]\]\s+)?(.+)$/);
    const body = bullet ? bullet[1] : line;
    if (!bullet && /^[>|]/.test(line)) {
      skipped += 1;
      continue;
    }
    const result = classifyBullet(body, sectionEntity);
    if (result.skip) {
      skipped += 1;
      continue;
    }
    candidates.push(...result.candidates);
  }

  return { ok: true, candidates, skipped, sourcePath };
}

export function discoverWorkbuddyFiles(cwd = "") {
  return discoverExternalFiles(cwd).filter((row) => row.family === "WorkBuddy");
}

export function discoverExternalFiles(cwd = "") {
  const home = homedir();
  const rows = [
    { id: "user", family: "WorkBuddy", path: join(home, ".workbuddy", "MEMORY.md") },
    { id: "workspace", family: "WorkBuddy", path: cwd ? join(cwd, ".workbuddy", "memory", "MEMORY.md") : "" },
    { id: "workspaceRoot", family: "WorkBuddy", path: cwd ? join(cwd, ".workbuddy", "MEMORY.md") : "" },
    { id: "claude-user", family: "Claude Code", path: join(home, ".claude", "CLAUDE.md") },
    { id: "claude-workspace", family: "Claude Code", path: cwd ? join(cwd, "CLAUDE.md") : "" },
    { id: "claude-dot", family: "Claude Code", path: cwd ? join(cwd, ".claude", "CLAUDE.md") : "" },
    { id: "codex-user", family: "Codex", path: join(home, ".codex", "AGENTS.md") },
    { id: "codex-workspace", family: "Codex", path: cwd ? join(cwd, "AGENTS.md") : "" },
    { id: "codex-dot", family: "Codex", path: cwd ? join(cwd, ".codex", "AGENTS.md") : "" },
  ];
  return rows
    .filter((row) => row.path)
    .map((row) => {
      const exists = existsSync(row.path);
      let bytes = 0;
      if (exists) {
        try {
          bytes = statSync(row.path).size;
        } catch {
          bytes = 0;
        }
      }
      return { ...row, exists, bytes };
    });
}

function readIfExists(path) {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * One-shot import of discovered curated markdown (WorkBuddy / Claude Code / Codex).
 * No watch, no reverse sync. Session jsonl dumps are not imported.
 */
export function importExternal(db, { cwd = "", ids } = {}) {
  const found = discoverExternalFiles(cwd);
  const want = Array.isArray(ids) && ids.length ? new Set(ids) : null;
  const files = found.filter((f) => f.exists && (!want || want.has(f.id)));
  if (!files.length) {
    return {
      ok: false,
      message:
        "No curated memory files found (WorkBuddy MEMORY.md, Claude Code CLAUDE.md, Codex AGENTS.md).",
      created: 0,
      merged: 0,
      skipped: 0,
      files: found,
    };
  }

  const candidates = [];
  let skipped = 0;
  const used = [];
  for (const file of files) {
    const text = readIfExists(file.path);
    if (text == null) continue;
    const parsed = parseWorkbuddyMarkdown(text, { sourcePath: file.path });
    if (!parsed.ok) {
      return { ...parsed, created: 0, merged: 0, files: found };
    }
    skipped += parsed.skipped;
    candidates.push(...parsed.candidates);
    used.push({
      id: file.id,
      family: file.family,
      path: file.path,
      bytes: file.bytes,
      parsed: parsed.candidates.length,
    });
  }

  const applied = applyCandidates(db, candidates, { via: "external-import" });
  const created = applied.filter((a) => a.action === "insert").length;
  const merged = applied.filter((a) => a.action === "merge").length;
  const dropped = Math.max(0, candidates.length - applied.length);
  return {
    ok: true,
    created,
    merged,
    linked: applied.filter((a) => a.type !== "entity").length,
    skipped: skipped + dropped,
    applied: applied.length,
    maxWriteChars: MAX_WRITE_CHARS,
    maxWriteItems: MAX_WRITE_ITEMS,
    files: found,
    used,
  };
}

/**
 * One-shot import of discovered WorkBuddy MEMORY.md files. No watch, no reverse sync.
 */
export function importWorkbuddy(db, { cwd = "", ids } = {}) {
  const found = discoverWorkbuddyFiles(cwd);
  const want = Array.isArray(ids) && ids.length ? new Set(ids) : null;
  const pick = found.filter((f) => f.exists && (!want || want.has(f.id))).map((f) => f.id);
  if (!pick.length) {
    return {
      ok: false,
      message: "没有找到 ~/.workbuddy/MEMORY.md 或工作区 .workbuddy/memory/MEMORY.md",
      created: 0,
      merged: 0,
      skipped: 0,
      files: found,
    };
  }
  const result = importExternal(db, { cwd, ids: pick });
  return { ...result, files: found };
}
